### ISSUE TITLE
After running main_track.py, I get a strange trajectory.

### ISSUE THREAD

**Issue by zhchyang2004** [Shunichi09/linear_nonlinear_control#1]
Hi, 
After running mpc/extend/main_track.py, I get a strange trajectory which is different to the 'Expected Results' on your page. Has the code been verified?

Regarding 'extended_MPC.py', in Line 105, the multiplication sequence is reversed aginst the  formular in the reference thesis. 

From Line 115 to 128, the codes seems also not compliance with the coefficient matrix of the reference .

Do you think the strange trajectory is caused by above issues?

Thanks!

**Comment by Shunichi09** [comment]
I'm sorry for late reply.
I checked my program and also got the strange trajectory.
I think this is caused by the weight of the evaluation functions like Q and R.
Therefore, I fixed this bug. please check the main_track.py and clone or fork.
I hope you can get correct results. Thank you for your issues.
